# Generated by Django 5.2.9 on 2026-04-04 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_tee_color"),
        ("events", "0024_alter_tournamentresult_summary"),
        ("register", "0018_registrationchangelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventPairing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tee_time", models.CharField(max_length=20, verbose_name="Tee time")),
                (
                    "group_ggid",
                    models.CharField(max_length=40, verbose_name="Golf Genius group id"),
                ),
                (
                    "pairing_group_id",
                    models.CharField(max_length=40, verbose_name="Golf Genius pairing group id"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pairings",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairings",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "hole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pairings",
                        to="courses.hole",
                        verbose_name="Hole",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairings",
                        to="register.player",
                        verbose_name="Player",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairings",
                        to="events.round",
                        verbose_name="Round",
                    ),
                ),
                (
                    "tee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pairings",
                        to="courses.tee",
                        verbose_name="Tee",
                    ),
                ),
            ],
            options={
                "db_table": "events_eventpairing",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("round", "player"), name="unique_round_player_pairing"
                    )
                ],
            },
        ),
    ]
