# Generated by Django 5.2.9 on 2026-03-30 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0024_alter_tournamentresult_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Session name")),
                ("registration_limit", models.IntegerField(verbose_name="Registration limit")),
                ("display_order", models.IntegerField(verbose_name="Display order")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="EventSessionFee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Amount"),
                ),
                (
                    "event_fee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.eventfee",
                        verbose_name="Event Fee",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_overrides",
                        to="events.eventsession",
                        verbose_name="Session",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="eventsession",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="unique_event_session_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventsession",
            constraint=models.UniqueConstraint(
                fields=("event", "display_order"), name="unique_event_session_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventsessionfee",
            constraint=models.UniqueConstraint(
                fields=("session", "event_fee"), name="unique_session_eventfee"
            ),
        ),
    ]
