# Generated by Django 5.2.9 on 2026-04-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0025_eventpairing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpairing",
            name="group_ggid",
            field=models.CharField(max_length=10, verbose_name="Golf Genius group id"),
        ),
        migrations.AlterField(
            model_name="eventpairing",
            name="pairing_group_id",
            field=models.CharField(max_length=22, verbose_name="Golf Genius pairing group id"),
        ),
    ]
