# Generated by Django 5.2.9 on 2026-04-06 22:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0025_eventsession_eventsessionfee_and_more"),
        ("events", "0026_alter_eventpairing_field_lengths"),
    ]

    operations = []
