# Generated by Django 5.2.9 on 2026-06-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0027_merge_20260406_1711"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="format",
            field=models.CharField(max_length=20, verbose_name="Format"),
        ),
    ]
