# Generated by Django 5.2.9 on 2026-08-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0028_alter_tournament_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="gg_spec_id",
            field=models.CharField(
                blank=True,
                max_length=22,
                null=True,
                verbose_name="Golf Genius id: tournament_spec_id",
            ),
        ),
    ]
