packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - "@nestjs/core"
  - better-sqlite3
