# Generated by Django 5.2.9 on 2026-03-28 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0024_alter_tournamentresult_summary"),
        ("register", "0017_remove_registration_starting_hole_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationChangeLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=20, verbose_name="Action")),
                ("is_admin", models.BooleanField(default=False, verbose_name="Is Admin")),
                ("details", models.JSONField(verbose_name="Details")),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created date"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="register.registration",
                        verbose_name="Registration",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_date",),
            },
        ),
    ]
