# Generated by Django 5.2.9 on 2026-03-30 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0025_eventsession_eventsessionfee_and_more"),
        ("register", "0018_registrationchangelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationslot",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="slots",
                to="events.eventsession",
                verbose_name="Session",
            ),
        ),
    ]
