FROM node:24-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.json ./
COPY apps/admin/package.json ./apps/admin/
COPY packages/domain/package.json ./packages/domain/

RUN pnpm install

COPY packages/domain ./packages/domain
RUN pnpm --filter @repo/domain build

COPY apps/admin ./apps/admin

WORKDIR /app/apps/admin

EXPOSE 3100

CMD ["pnpm", "dev"]
