# Generated by Django 5.2.9 on 2026-02-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_tee"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
