# Generated by Django 5.2.9 on 2026-02-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_course_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="tee",
            name="color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
