# Generated by Django 4.2 on 2026-01-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_staticdocument_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubDocumentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Code')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Club Document Code',
                'ordering': ['display_name'],
            },
        ),
    ]
