# Generated by Django 4.2 on 2026-01-25

from django.db import migrations


CLUB_DOCUMENT_CODES = [
    {"code": "BYLAW", "display_name": "Club By-Laws", "location": "Home Page"},
    {"code": "CUP", "display_name": "Dam Cup Standings", "location": "Dam Cup Page"},
    {"code": "TUT1", "display_name": "Event Registration Guide", "location": "Home Page"},
    {"code": "TUT2", "display_name": "Event Scoring Guide", "location": "Home Page"},
    {"code": "HCP", "display_name": "Handicap Calculator", "location": "Home Page"},
    {"code": "SLPG", "display_name": "Season Long Points Gross Standings", "location": "SLP Page"},
    {"code": "SLPN", "display_name": "Season Long Points Net Standings", "location": "SLP Page"},
    {"code": "FIN", "display_name": "Treasurer Report", "location": "Home Page"},
    {"code": "SO", "display_name": "Special Order Information", "location": "Home Page"},
    {"code": "ACCTS", "display_name": "Special Order Accounts", "location": "Home Page"},
]


def seed_club_document_codes(apps, schema_editor):
    ClubDocumentCode = apps.get_model('documents', 'ClubDocumentCode')
    for item in CLUB_DOCUMENT_CODES:
        ClubDocumentCode.objects.get_or_create(
            code=item["code"],
            defaults={
                "display_name": item["display_name"],
                "location": item["location"],
            }
        )


def reverse_noop(apps, schema_editor):
    # No-op reverse - keep data on rollback
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_clubdocumentcode'),
    ]

    operations = [
        migrations.RunPython(seed_club_document_codes, reverse_noop),
    ]
