# Generated by Django 5.2.9 on 2026-01-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0008_seed_clubdocumentcodes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubdocumentcode",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
