# Generated by Django 5.2.9 on 2026-01-31 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0005_remove_eventscore_unique_event_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventscore",
            name="scorecard",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="scores.eventscorecard",
                verbose_name="Scorecard",
            ),
            preserve_default=False,
        ),
    ]
