FROM node:24-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.json ./
COPY apps/api/package.json ./apps/api/
COPY packages/domain/package.json ./packages/domain/

RUN pnpm install --frozen-lockfile

COPY packages/domain ./packages/domain
RUN pnpm --filter @repo/domain build

WORKDIR /app/apps/api

EXPOSE 3333
EXPOSE 9229

CMD ["pnpm", "debug"]
